---
version: '2'
services:
  api:
    image: bank/api
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/api
    depends_on:
      - db
  db:
    image: postgres:10
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"